# Configuration for Multiple Personas (Short Duration)
# Qwen3-32B with 8bit quantization, multiple personas, short diary generation

# Model settings
model:
  name: "Qwen/Qwen3-14B"

  quantization:
    enabled: true
    # type: "8bit"
    load_in_8bit: true
    load_in_4bit: false

  dtype: "bfloat16"
  device_map: "auto"

# Generation settings
generation:
  max_new_tokens: 200
  temperature: 0.7
  top_p: 0.8
  top_k: 20
  do_sample: true

# Thinking mode settings
thinking:
  enabled: false  # Disable for faster generation

# Data generation settings (short duration for multiple personas)
data:
  num_baseline_days: 3    # Reduced duration before loss
  num_grief_days: 3       # Reduced duration after loss
  loss_day: 4             # Loss event occurs on day 4
  base_dir: "data"

# Expected data volume:
# 5 personas × 6 diaries × ~150 tokens/diary = ~4,500 tokens
# Adjust SAE training config if more data is needed
